monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: php://stderr
            level: debug
            formatter: monolog.formatter.json
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        login:
            type: rotating_file
            max_files: 15
            path: "%kernel.logs_dir%/%kernel.environment%.auth.log"
            level: info
            channels: security
            #formatter:      'monolog.formatter.json'
        monitoring:
            type: rotating_file
            max_files: 15
            path: "%kernel.logs_dir%/%kernel.environment%.monitoring.txt"
            level: info
            channels: app
            formatter: 'monolog.formatter.json'
        main_error:
            type: fingers_crossed
            action_level: error
            handler: streamed_error
        streamed_error:
            type: rotating_file
            max_files: 15
            path: "%kernel.logs_dir%/%kernel.environment%.error.log"
            level: info
        main_critical:
            type: fingers_crossed
            action_level: critical
            handler: grouped_critical
        grouped_critical:
            type: group
            members: [ streamed_critical ]
        streamed_critical:
            type: rotating_file
            max_files: 15
            path: "%kernel.logs_dir%/%kernel.environment%.critical.log"
            level: info